language: ruby
rvm:
- 2.3.1
- 1.9.3
- jruby-19mode
- rbx-2

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp config/database.yml
  - psql -c 'create database casino_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rspec
